/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/sign-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description User created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: {
                                /**
                                 * @description User Id
                                 * @example user123
                                 */
                                id: string;
                                /**
                                 * Format: email
                                 * @description User email
                                 * @example user@email.com
                                 */
                                email: string;
                                /** @default [] */
                                memberships: {
                                    /**
                                     * @description A unique identifier string
                                     * @example abc123
                                     */
                                    tenantId: string;
                                    tenantName: string;
                                    /** @enum {string} */
                                    role: "owner" | "admin" | "member";
                                }[];
                                /** Format: date-time */
                                createdAt?: string;
                                /** Format: date-time */
                                updatedAt?: string;
                            };
                            message: string;
                            session?: {
                                /**
                                 * @description A unique identifier string
                                 * @example abc123
                                 */
                                currentTenantId?: string | null;
                            };
                        };
                    };
                };
                /** @description Conflict: User already exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                                requestId?: string | number;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description User signed in */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: {
                                /**
                                 * @description User Id
                                 * @example user123
                                 */
                                id: string;
                                /**
                                 * Format: email
                                 * @description User email
                                 * @example user@email.com
                                 */
                                email: string;
                                /** @default [] */
                                memberships: {
                                    /**
                                     * @description A unique identifier string
                                     * @example abc123
                                     */
                                    tenantId: string;
                                    tenantName: string;
                                    /** @enum {string} */
                                    role: "owner" | "admin" | "member";
                                }[];
                                /** Format: date-time */
                                createdAt?: string;
                                /** Format: date-time */
                                updatedAt?: string;
                            };
                            message: string;
                            session?: {
                                /**
                                 * @description A unique identifier string
                                 * @example abc123
                                 */
                                currentTenantId?: string | null;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/sign-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Signed out successfully */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                    favoritesOnly?: boolean | "true" | "false";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            documents: {
                                items: {
                                    /**
                                     * @description A unique identifier string
                                     * @example abc123
                                     */
                                    id: string;
                                    /**
                                     * @description Document title
                                     * @example Launch plan
                                     */
                                    title: string;
                                    /** Format: date-time */
                                    updatedAt?: string;
                                    /** @description Indicator whether the document is marked as favorite by the user */
                                    isFavorite: boolean;
                                }[];
                                total: number;
                            };
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                                requestId?: string | number;
                            };
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                                requestId?: string | number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Owning tenant identifier
                         * @example tenant_123
                         */
                        tenantId?: string;
                        /**
                         * @description Document title
                         * @example Launch plan
                         */
                        title?: string;
                        /**
                         * @description Creation source
                         * @default editor
                         * @enum {string}
                         */
                        source?: "editor" | "url";
                        /**
                         * Format: uri
                         * @description Original URL when the document was generated from a link
                         */
                        sourceUrl?: string | null;
                        /** @description Markdown or raw document body */
                        content?: string;
                        /**
                         * @description Additional metadata such as tags or ingestion info
                         * @default {}
                         */
                        metadata?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            responses: {
                /** @description Queued */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Document identifier assigned by the server
                             * @example doc_123
                             */
                            id?: string;
                            /**
                             * @description Owning tenant identifier
                             * @example tenant_123
                             */
                            tenantId: string;
                            /**
                             * @description Document title
                             * @example Launch plan
                             */
                            title: string;
                            /**
                             * @description Creation source
                             * @default editor
                             * @enum {string}
                             */
                            source: "editor" | "url";
                            /**
                             * Format: uri
                             * @description Original URL when the document was generated from a link
                             */
                            sourceUrl?: string | null;
                            /** @description Markdown or raw document body */
                            content?: string;
                            /**
                             * @description Additional metadata such as tags or ingestion info
                             * @default {}
                             */
                            metadata: {
                                [key: string]: unknown;
                            };
                            /**
                             * @description User who created the document
                             * @example abc123
                             */
                            createdById?: string;
                            /**
                             * @description User who last updated the document
                             * @example abc123
                             */
                            updatedById?: string;
                            /** Format: date-time */
                            createdAt?: string;
                            /** Format: date-time */
                            updatedAt?: string;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                                requestId?: string | number;
                            };
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                                requestId?: string | number;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    /** @description Tenant ID to scope the search */
                    tenantId: string;
                    q: string;
                    /** @description Maximum number of results to return */
                    limit?: number;
                    /** @description Number of results to skip for pagination */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Total number of matched items
                             * @example 100
                             */
                            total: number;
                            items: {
                                /**
                                 * @description A unique identifier string
                                 * @example abc123
                                 */
                                id: string;
                                /** @example typescript documentation 1 */
                                title: string;
                                /**
                                 * @description A short snippet of the matched content
                                 * @example TypeScript is a typed superset of JavaScript that compiles to plain JavaScript...
                                 */
                                snippet?: string;
                                /**
                                 * @description Relevance score for ranking
                                 * @example 0.95
                                 */
                                score?: number;
                                /**
                                 * @description Link to the full document or resource
                                 * @example https://www.typescriptlang.org/docs/
                                 */
                                url?: string;
                            }[];
                            /**
                             * @description Page number, starting from 1
                             * @default 1
                             * @example 1
                             */
                            page: number;
                            /**
                             * @description Number of items per page, max 100
                             * @default 10
                             * @example 10
                             */
                            pageSize: number;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                                requestId?: string | number;
                            };
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                                requestId?: string | number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List tenants the current user belongs to */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            tenants: {
                                /**
                                 * @description A unique identifier string
                                 * @example abc123
                                 */
                                tenantId: string;
                                /**
                                 * @description Name of the tenant
                                 * @example Software Inc
                                 */
                                tenantName: string;
                                /**
                                 * @default member
                                 * @enum {string}
                                 */
                                role: "owner" | "admin" | "member";
                            }[];
                            /**
                             * @description A unique identifier string
                             * @example abc123
                             */
                            activeTenantId?: string | null;
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                                requestId?: string | number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Name of the tenant
                         * @example Software Inc
                         */
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Tenant ID
                             * @example tenant123
                             */
                            id: string;
                            /**
                             * @description Name of the tenant
                             * @example Software Inc
                             */
                            name: string;
                            /** Format: date-time */
                            createdAt?: string;
                            /** Format: date-time */
                            updatedAt?: string;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                                requestId?: string | number;
                            };
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                                requestId?: string | number;
                            };
                        };
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                                requestId?: string | number;
                            };
                        };
                    };
                };
            };
        };
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Tenant ID to remove
                         * @example abc123
                         */
                        id: string;
                    };
                };
            };
            responses: {
                /** @description Success */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                                requestId?: string | number;
                            };
                        };
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                                requestId?: string | number;
                            };
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tenants/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Tenant ID
                         * @example tenant123
                         */
                        id: string;
                    };
                };
            };
            responses: {
                /** @description Success */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                                requestId?: string | number;
                            };
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                                requestId?: string | number;
                            };
                        };
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                                requestId?: string | number;
                            };
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: unknown;
                                requestId?: string | number;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
